# Generated by Django 3.1.6 on 2021-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210209_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
