# Generated by Django 3.1.6 on 2021-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210208_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='product',
        ),
        migrations.AlterField(
            model_name='images',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Receiving',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
